include:
  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '.gitlab-ci/build-nix.yml'
    inputs:
      job-name: 'build-adaptio'
      nix-attribute: '.#adaptio'
    rules:
      - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - src/**/*
          - cmake/**/*
          - flake.{nix,lock}
          - CMakeLists.txt
          - assets/**/*
          - tests/**/*
          - version.txt

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '.gitlab-ci/nix-adaptio-test.yml'
    inputs:
      job-name: 'unit-tests'
      nix-attribute: '.#adaptio-tests'
      test-target: 'adaptio-unit-tests'
      test-output: 'unit-tests-report.xml'
    rules:
      - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - src/**/*
          - cmake/**/*
          - flake.{nix,lock}
          - CMakeLists.txt
          - assets/**/*
          - tests/**/*

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '.gitlab-ci/nix-adaptio-test.yml'
    inputs:
      job-name: 'block-tests'
      nix-attribute: '.#adaptio-tests'
      test-target: 'adaptio-block-tests'
      test-output: 'block-tests-report.xml'
    rules:
      - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - src/**/*
          - cmake/**/*
          - flake.{nix,lock}
          - CMakeLists.txt
          - assets/**/*
          - tests/**/*

  - local: '.gitlab-ci/lints.yml'
    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - src/**/*.{cc,h}
          - .clang-format

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/check-nix.yml'
    inputs:
      job-rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          interruptible: true
        - when: on_success
    rules:
      - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      - changes:
          - flake.{nix,lock}

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/lint-version.yml'
    inputs:
      job-rules:
        - if: '$CI_COMMIT_REF_PROTECTED == "true"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  - project: 'esab/abw/infra-and-test'
    ref: main
    file:
      - '/.gitlab-ci/lint-commit.yml'
      - '/.gitlab-ci/lint-shellscript.yml'
      - '/.gitlab-ci/lint-markdown-cli2.yml'
      - '/.gitlab-ci/lint-python.yml'
      - '/.gitlab-ci/k8-runner-defaults.yml'
      - '/.gitlab-ci/variables.yml'
      - '/.gitlab-ci/semver-version.yml'

  - project: 'esab/abw/infra-and-test'
    ref: main
    file: '/.gitlab-ci/trigger-flake-update.yml'
    inputs:
      job-rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      target-project-name: 'adaptio-os'
      nix-input-name: 'adaptio-software'

  - project: 'esab/abw/infra-and-test'
    ref: main
    file:
      - '/.gitlab-ci/update-flake-inputs.yml'
    inputs:
      job-rules:
        - if: '$CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_REF_PROTECTED == "true"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
      ignore-breaking-change: true

default:
  interruptible: false

workflow:
  name: '$PIPELINE_NAME'
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TITLE =~ /^chore\(semver\): Bump.*/'
      variables:
        PIPELINE_NAME: 'Pipeline for new version: $CI_COMMIT_REF_NAME'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      variables:
        PIPELINE_NAME: 'Triggered by pipeline for branch: $CI_COMMIT_REF_NAME'
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TITLE !~ /^chore\(semver\): Bump.*/'
      variables:
        PIPELINE_NAME: 'Pipeline for protected branch: $CI_COMMIT_REF_NAME'

stages:
  - lint
  - check
  - build
  - test
