clang-format:
  extends: .k8-adaptio-defaults
  stage: lint
  script:
    - source $GITLAB_SHARED_FUNCS
    - section_start lint "Run clang format"
    - shopt -s globstar # Required for ** to be recursive in bash
    - nix develop -c clang-format --version
    - nix develop -c clang-format --Werror --dry-run --verbose src/**/*.cc src/**/*.h
    - section_end lint
