if (EXISTS "$ENV{Pylon_ROOT}")
  message(PYLON_ROOT="$ENV{Pylon_ROOT}")
  set(Pylon_FOUND TRUE)
  set(Pylon_INCLUDE_DIR "$ENV{Pylon_ROOT}/include")
  set(Pylon_LIBRARIES "pylonbase;pylonutility;GenApi_gcc_v3_1_Basler_pylon;GCBase_gcc_v3_1_Basler_pylon")

  set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  link_directories("$ENV{Pylon_ROOT}/lib")
else ()
  if (APPLE AND EXISTS /Library/Frameworks/pylon.framework)
    set(Pylon_FOUND TRUE)
    set(Pylon_INCLUDE_DIR /Library/Frameworks/pylon.framework/Headers/GenICam)
    set(Pylon_LIBRARIES "pylonbase;pylonutility;GenApi_gcc_v3_1_Basler_pylon;GCBase_gcc_v3_1_Basler_pylon")

    list(APPEND CMAKE_BUILD_RPATH /Library/Frameworks/pylon.framework/Libraries)
  else ()
    set(Pylon_FOUND FALSE)
  endif ()
endif ()
